#!/usr/bin/env bash
# build_corpus.sh — build the premise index the pre-flight queries.
#
# Two sources, and they see different things. A regular expression over source
# files finds what is written down; the elaborated environment knows what the
# checker knows. Measured on one installation: 182,025 against 330,887. The gap
# is everything produced by an attribute, generated by a macro, or living in a
# core library outside the scanned tree — and that is where most of the results
# anyone cites actually live.
#
# The environment dump needs a built project and takes minutes. It is a one-time
# index build, not something a campaign pays for, and the result is pinned by
# hash so a later run can tell whether the library moved underneath it.
#
# Usage:
#   build_corpus.sh --out <corpus.json>              # both, merged
#   build_corpus.sh --out <corpus.json> --source-only
#
# Needs WITSOC2_LEAN_PROJECT for the environment dump.

set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PACK="$(dirname "$HERE")"

OUT=""; SOURCE_ONLY=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    --out) OUT="$2"; shift 2 ;;
    --source-only) SOURCE_ONLY=1; shift ;;
    -h|--help) sed -n '2,20p' "$0"; exit 0 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done
[[ -n "$OUT" ]] || { echo "--out is required" >&2; exit 2; }

PROJECT="${WITSOC2_LEAN_PROJECT:-}"
SRC=""
[[ -n "$PROJECT" && -d "$PROJECT/Mathlib" ]] && SRC="$PROJECT/Mathlib"

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

if [[ -n "$SRC" ]]; then
  echo "[corpus] source scan over $SRC" >&2
  python3 "$HERE/corpus.py" build --src "$SRC" --out "$TMP/source.json" >&2
else
  echo "[corpus] no project set; skipping the source scan" >&2
fi

if [[ "$SOURCE_ONLY" -eq 1 || -z "$PROJECT" ]]; then
  if [[ -f "$TMP/source.json" ]]; then
    cp "$TMP/source.json" "$OUT"
    echo "[corpus] wrote $OUT from the source scan alone — it will report ABSENT for" >&2
    echo "         declarations the library has but does not spell out. That is a report," >&2
    echo "         not a verdict, and the pre-flight says so." >&2
    exit 0
  fi
  echo "[corpus] nothing to build" >&2; exit 2
fi

echo "[corpus] dumping the elaborated environment (minutes; one-time)" >&2
( cd "$PROJECT" && lake env lean "$HERE/lean/DumpNames.lean" ) > "$TMP/names.tsv"
echo "[corpus] $(wc -l < "$TMP/names.tsv") declarations from the environment" >&2

if [[ -f "$TMP/source.json" ]]; then
  python3 "$HERE/corpus.py" build-from-env --index "$TMP/names.tsv" \
      --merge-types-from "$TMP/source.json" --out "$OUT"
else
  python3 "$HERE/corpus.py" build-from-env --index "$TMP/names.tsv" --out "$OUT"
fi
echo "[corpus] set WITSOC2_MATHS_CORPUS=$OUT so produce.py uses it" >&2
