#!/usr/bin/env python3
"""Premise corpus — pinned retrieval over a declaration index.

Replaces guessing with three honest verdicts:

    KNOWN          resolved name, type, and module
    SEARCH_TARGET  plausibly exists, unresolved — a lead, never a premise
    ABSENT         not in the corpus; establishing it is a sub-claim

**Two builders, and they see different things.**

`build` scans source with a regular expression. `build-from-env` reads an index
dumped from the elaborated environment by `scripts/lean/DumpNames.lean`, which is
what the checker itself knows. Measured on this installation: **182,025 against
467,557**. The difference is everything produced by an attribute, generated by a
macro, or living in a core library outside the scanned tree — and that is where
most of the results anyone cites actually live.

Prefer the environment index. The source scan is the fallback for when no
toolchain is available, and its limits are these: Names
generated by attributes, produced by macros, or inherited from a core library
outside the scanned tree are ABSENT here and may exist perfectly well. That is
why ABSENT is a report and not a refusal: `premise_preflight.py` warns and lets
the run continue, because a pre-flight that blocked what it could not resolve
would teach people to stop citing anything it does not know — the opposite of
what a premise ledger is for.

Namespaces are tracked, so a declaration inside `namespace X` is indexed as
`X.name` and cited that way. Indexing the bare name meant every qualified
citation missed, which is the form people actually write.

The reverse also happens, and more often: under `open Nat` people cite
`add_comm`, not `Nat.add_comm`, because that is what Lean prints. So a name
that does not match in full is looked up by suffix, and resolved only when
exactly ONE declaration ends in it. More than one is reported as a
SEARCH_TARGET listing them — ambiguity is a question for the author, not
something to pick a winner from. Measured on 800 citations lifted from real
proofs: 380 matched in full, 130 more by unique suffix, 5 were ambiguous.

Two rules make this more than a lookup:

  * The corpus is PINNED. Its sha256 is computed over the canonical manifest and
    checked on every query. A hit whose fields differ from the snapshot is a
    drift error, not a result — otherwise a live index can silently change what
    a recorded proof depended on.
  * An empty result is INFORMATION, not a reason to fall back to a zero-score
    guess. It usually means the formulation does not match how the library
    states the concept, which is a reframing signal.

Feasibility is structural only. FEASIBLE means every query got a candidate and
every dependency closed — it does not assert that the premises entail anything.

The index is read from `--corpus`, else `WITSOC2_MATHS_CORPUS`, else
`WITSOC2_PREMISE_CORPUS`. Both names are accepted because both were in print;
the first is the one the builder and `produce.py` advertise.

Usage:
    corpus.py build --src <dir> --out <corpus.json>          (source scan)
    corpus.py build-from-env --index <names.tsv> --out <corpus.json>   (elaborated)
    corpus.py query <q> [<q> ...] [--corpus C] [--top 10] [--json]
    corpus.py feasibility --queries <f.json> [--corpus C] [--imports ...] [--json]
"""
from __future__ import annotations
import argparse, hashlib, json, os, re, sys
from pathlib import Path

SCHEMA = "maths.premise_corpus.v1"
REQUIRED = ("name","type","statement","module","imports","dependencies","aliases")
NOTATION = {"∑":"Finset.sum","∏":"Finset.prod","∣":"Dvd.dvd","≤":"LE.le","≥":"GE.ge",
            "∈":"Membership.mem","∀":"forall","∃":"Exists"}

def canonical(decls: list[dict]) -> str:
    ordered = sorted(decls, key=lambda d: d["name"])
    return json.dumps({"schema": SCHEMA, "declarations": ordered},
                      sort_keys=True, separators=(",", ":"), ensure_ascii=True)

def corpus_sha(decls: list[dict]) -> str:
    return hashlib.sha256(canonical(decls).encode()).hexdigest()

def tokens(text: str) -> set[str]:
    for sym, name in NOTATION.items():
        text = text.replace(sym, f" {name} ")
    return {t for t in re.split(r"[^A-Za-z0-9_.]+", text.lower()) if len(t) > 1}

def symbol_overlap(query: str, decl: dict) -> float:
    """Directional: `Nat.divisors_eq` provides for `Nat.divisors`, but the bare
    namespace `Nat` must not match a specific lemma."""
    qsyms = set(re.findall(r"\b([A-Z][A-Za-z0-9_]*(?:\.[A-Za-z_]\w*)+)\b", query))
    if not qsyms: return 0.0
    name = decl["name"]
    return sum(1 for q in qsyms if name.startswith(q) or q in name) / len(qsyms)

def load_corpus(path: str | None) -> tuple[list[dict], str | None, str | None]:
    # Two names reached print: the builder and produce.py advertise
    # WITSOC2_MATHS_CORPUS, this reader only ever read WITSOC2_PREMISE_CORPUS.
    # Following the documented setup therefore produced an all-SEARCH_TARGET
    # report that looked like a finding. Accept both; MATHS is canonical.
    path = path or os.environ.get("WITSOC2_MATHS_CORPUS") \
                or os.environ.get("WITSOC2_PREMISE_CORPUS")
    if not path or not Path(path).exists():
        return [], None, None
    data = json.loads(Path(path).read_text(encoding="utf-8"))
    decls = data.get("declarations", [])
    recorded = data.get("corpus_sha256")
    actual = corpus_sha(decls)
    if recorded and recorded != actual:
        return decls, recorded, actual   # caller reports drift
    return decls, recorded, None

_SUFFIX_CACHE: dict[int, dict[str, list[str]]] = {}


def suffix_index(decls: list[dict]) -> dict[str, list[str]]:
    """Every proper suffix of every declaration name, mapped to what has it."""
    key = id(decls)
    cached = _SUFFIX_CACHE.get(key)
    if cached is None:
        cached = {}
        for d in decls:
            parts = d["name"].split(".")
            for i in range(1, len(parts)):
                cached.setdefault(".".join(parts[i:]), []).append(d["name"])
        _SUFFIX_CACHE[key] = cached
    return cached


_TOKEN_CACHE: dict[int, list[set]] = {}


def decl_tokens(decls: list[dict]) -> list[set]:
    """Tokenize the corpus ONCE per load, not once per query.

    Every unresolved citation triggered a full re-tokenization of every
    declaration. At 61k that was a second; at 467k a handful of unresolved
    names took minutes, and a pre-flight nobody waits for is a pre-flight
    nobody runs.
    """
    key = id(decls)
    cached = _TOKEN_CACHE.get(key)
    if cached is None or len(cached) != len(decls):
        cached = [tokens(" ".join(str(d.get(k, "")) for k in
                                  ("name", "type", "statement", "module"))
                         + " " + " ".join(d.get("aliases", []))) for d in decls]
        _TOKEN_CACHE[key] = cached
    return cached


def search(query: str, decls: list[dict], top: int) -> list[dict]:
    qt = tokens(query)
    cache = decl_tokens(decls)
    scored = []
    for d, dt in zip(decls, cache):
        jaccard = len(qt & dt) / len(qt | dt) if (qt | dt) else 0.0
        score = jaccard + 0.5 * symbol_overlap(query, d)
        if score > 0:
            scored.append({"name": d["name"], "type": d.get("type"),
                           "module": d.get("module"), "score": round(score, 4)})
    return sorted(scored, key=lambda s: (-s["score"], s["name"]))[:top]

def build(src: str) -> list[dict]:
    """Index declarations under their QUALIFIED names.

    A declaration written inside `namespace Nat` is `Nat.foo` everywhere it is
    cited, and the source says only `foo`. Indexing the bare name meant a
    premise pre-flight asking about `Nat.add_zero` matched nothing and reported
    SEARCH_TARGET for a result the library plainly has — a lookup that cannot
    resolve the form people actually write is a lookup nobody will trust twice.

    Namespaces nest and close with `end`, so the scanner carries a stack. Both
    forms are recorded: the qualified name to match a citation, and the bare one
    as an alias to match a search.
    """
    decls = []
    RE_NAMESPACE = re.compile(r"^\s*namespace\s+([\w.']+)", re.MULTILINE)
    RE_END = re.compile(r"^\s*end\b\s*([\w.']*)", re.MULTILINE)
    RE_DECL = re.compile(r"^\s*(?:@\[[^\]]*\]\s*)?(?:private\s+|protected\s+|nonrec\s+)*"
                         r"(?:theorem|lemma)\s+([\w.']+)\s*(.*?):=",
                         re.MULTILINE | re.DOTALL)
    for path in sorted(Path(src).rglob("*.lean")):
        try:
            text = path.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        module = str(path.relative_to(src)).replace("/", ".")[:-5]
        imports = re.findall(r"^\s*import\s+([\w.]+)", text, re.MULTILINE)

        # One pass over the events that change scope, in source order.
        events = []
        for m in RE_NAMESPACE.finditer(text):
            events.append((m.start(), "open", m.group(1)))
        for m in RE_END.finditer(text):
            events.append((m.start(), "close", m.group(1)))
        for m in RE_DECL.finditer(text):
            events.append((m.start(), "decl", m))
        events.sort(key=lambda e: e[0])

        stack: list[str] = []
        for _, kind, payload in events:
            if kind == "open":
                stack.append(payload)
            elif kind == "close":
                if stack:
                    stack.pop()
            else:
                bare = payload.group(1)
                qualified = ".".join(stack + [bare]) if stack else bare
                body = " ".join(payload.group(2).split())[:400]
                decls.append({"name": qualified, "type": body, "statement": body,
                              "module": module, "imports": imports,
                              "dependencies": [],
                              "aliases": [bare] if qualified != bare else []})
    return decls

def build_from_env(index_path: str) -> list[dict]:
    """Read a TSV dumped from the elaborated environment.

    No types here by design: retrieval asks whether a name exists, and pretty-
    printing three hundred thousand types costs minutes for information that
    only affects ranking. `build` keeps the types for the declarations it can
    parse, and a caller wanting both can merge — the honest default is the
    complete name index over the partial typed one, because a resolution that
    says ABSENT for something the library has is worse than one that resolves
    without a type to show.
    """
    decls = []
    for line in Path(index_path).read_text(encoding="utf-8").splitlines():
        parts = line.split("\t")
        if len(parts) < 3 or not parts[0].strip():
            continue
        name, module, kind = parts[0].strip(), parts[1].strip(), parts[2].strip()
        bare = name.rsplit(".", 1)[-1]
        decls.append({
            "name": name, "type": "", "statement": "", "module": module,
            "kind": kind, "imports": [module] if module else [],
            "dependencies": [], "aliases": [bare] if bare != name else [],
            "source": "elaborated-environment",
        })
    return decls


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    sub = ap.add_subparsers(dest="cmd", required=True)
    b = sub.add_parser("build"); b.add_argument("--src", required=True); b.add_argument("--out", required=True)
    e = sub.add_parser("build-from-env")
    e.add_argument("--index", required=True,
                   help="TSV from scripts/lean/DumpNames.lean")
    e.add_argument("--out", required=True)
    e.add_argument("--merge-types-from",
                   help="a corpus.json built by `build`, to carry its types across")
    q = sub.add_parser("query"); q.add_argument("queries", nargs="+")
    q.add_argument("--corpus"); q.add_argument("--top", type=int, default=10)
    q.add_argument("--json", action="store_true")
    f = sub.add_parser("feasibility"); f.add_argument("--queries", required=True)
    f.add_argument("--corpus"); f.add_argument("--imports", nargs="*")
    f.add_argument("--json", action="store_true")
    a = ap.parse_args()

    if a.cmd == "build-from-env":
        decls = build_from_env(a.index)
        if a.merge_types_from and Path(a.merge_types_from).is_file():
            # Types from the source scan, names from the environment. Neither is
            # complete on its own and the failure modes are opposite: the scan
            # misses declarations, the dump misses their types.
            typed = {d["name"]: d for d in
                     json.loads(Path(a.merge_types_from).read_text(encoding="utf-8"))
                     .get("declarations", [])}
            carried = 0
            for decl in decls:
                match = typed.get(decl["name"]) or typed.get(decl["name"].rsplit(".", 1)[-1])
                if match and match.get("type"):
                    decl["type"] = match["type"]
                    decl["statement"] = match.get("statement", match["type"])
                    carried += 1
            print(f"carried {carried} type(s) across from the source scan", file=sys.stderr)
        payload = {"schema": SCHEMA, "index_revision": "elaborated-environment",
                   "declarations": sorted(decls, key=lambda d: d["name"]),
                   "corpus_sha256": corpus_sha(decls)}
        Path(a.out).write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
        print(f"built {a.out}: {len(decls)} declarations from the elaborated environment, "
              f"sha {payload['corpus_sha256'][:16]}...")
        return 0

    if a.cmd == "build":
        decls = build(a.src)
        payload = {"schema": SCHEMA, "index_revision": "local",
                   "declarations": sorted(decls, key=lambda d: d["name"]),
                   "corpus_sha256": corpus_sha(decls)}
        Path(a.out).write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
        print(f"built {a.out}: {len(decls)} declarations, sha {payload['corpus_sha256'][:16]}...")
        return 0

    decls, recorded, drift = load_corpus(a.corpus)
    if drift:
        print(f"ERROR: corpus drift — recorded {recorded[:16]}... actual {drift[:16]}...\n"
              "  A live index that changed under a recorded proof invalidates it.",
              file=sys.stderr)
        return 2

    queries = a.queries if a.cmd == "query" else json.loads(
        Path(a.queries).read_text(encoding="utf-8"))
    queries = queries if isinstance(queries, list) else queries.get("queries", [])

    # One pass to index, rather than a linear scan per query. At 61k
    # declarations the difference was invisible; at 467k a pre-flight over a
    # dozen citations took minutes, which is the same as not having the index.
    by_name = {d["name"]: d for d in decls}
    by_suffix = suffix_index(decls)
    results, unsupported = [], []
    for query in queries:
        if not decls:
            results.append({"query": query, "verdict": "SEARCH_TARGET", "candidates": [],
                "note": "no corpus configured (WITSOC2_MATHS_CORPUS) — unresolved "
                        "rather than guessed"})
            unsupported.append(query); continue
        exact = by_name.get(query)
        if exact:
            results.append({"query": query, "verdict": "KNOWN", "name": exact["name"],
                            "type": exact.get("type"), "module": exact.get("module")})
            continue
        # People write citations the way Lean prints them: relative to whatever
        # is open. Measured on 800 citations lifted from real Mathlib proofs,
        # 380 matched a full name and another 130 matched exactly one
        # declaration by suffix. Resolving those is not guessing — uniqueness
        # is the whole condition, and where it fails the candidates are
        # reported as leads instead.
        relative = by_suffix.get(query, [])
        if len(relative) == 1:
            hit = by_name[relative[0]]
            results.append({"query": query, "verdict": "KNOWN", "name": hit["name"],
                            "type": hit.get("type"), "module": hit.get("module"),
                            "resolved_from": "unique suffix match — the citation is written "
                                             "relative to an open namespace"})
            continue
        if len(relative) > 1:
            results.append({"query": query, "verdict": "SEARCH_TARGET",
                            "candidates": [{"name": n, "type": by_name[n].get("type"),
                                            "module": by_name[n].get("module"), "score": 1.0}
                                           for n in sorted(relative)[:10]],
                            "note": f"{len(relative)} declarations end in this name. Ambiguous "
                                    "is not resolved: qualify the citation"})
            continue
        hits = search(query, decls, a.top if a.cmd == "query" else 5)
        if hits:
            results.append({"query": query, "verdict": "SEARCH_TARGET", "candidates": hits,
                            "note": "named candidates are leads, not premises"})
        else:
            results.append({"query": query, "verdict": "ABSENT",
                            "note": "not in the corpus; establishing it is a sub-claim"})
            unsupported.append(query)

    out = {"corpus_declarations": len(decls), "corpus_sha256": recorded,
           "empty_result": not decls, "results": results}
    if a.cmd == "feasibility":
        out["unsupported_queries"] = unsupported
        out["feasibility"] = "FEASIBLE" if (decls and not unsupported) else "INFEASIBLE"
        out["reasons"] = ([] if out["feasibility"] == "FEASIBLE" else
            (["no corpus configured"] if not decls else
             [f"no candidate for: {q}" for q in unsupported]))
        out["note"] = ("structural only: FEASIBLE means every query found a candidate, "
                       "not that the premises entail the target")
    if a.json: print(json.dumps(out, indent=2))
    else:
        if not decls: print("  no corpus configured — every query is SEARCH_TARGET, never a guess\n")
        for r in out["results"]:
            print(f"  {r['verdict']:<14} {r['query']}" +
                  (f"  :  {r.get('type','')[:60]}" if r.get("type") else ""))
        if a.cmd == "feasibility":
            print(f"\n  feasibility: {out['feasibility']}")
            for reason in out["reasons"]: print(f"    {reason}")
    return 0

if __name__ == "__main__":
    sys.exit(main())
