-- Status: UNVERIFIED
MODULE [bad_case]

THEOREM [t]:
  CLAIM:
    something

PROOF OF [t]:
  [1] CASE $x > 0$:
    [1.1] HAVE positive branch.
          BY [1.0], algebra.
    [1] QED BY [1.1].
  [2] CASE $x < 0$:
    [2.1] HAVE uses the other case.
          BY [1.1], algebra.
    [2] QED BY [2.1].
  [3] SHOW done.
      BY [1], [2].
  QED BY [3].
