/-
Name index — what the checker knows exists.

Retrieval is a NAME lookup: `Nat.gcd_comm` either is a declaration or it is not,
and a pre-flight that cannot answer that is advisory noise. Types matter for
ranking and display and pretty-printing three hundred thousand of them takes
minutes, so the two are separated and the fast one answers the question
retrieval actually asks.

Measured on one installation: a regular expression over source files finds
182,025 declarations; the environment holds 330,887 theorems. The gap is
everything produced by an attribute, generated by a macro, or living in a core
library outside the scanned tree — and that is where most of the results anyone
cites actually live.

Two things here were learned by running it on a small import rather than the
whole library:

  * `Lean.Elab.Command` is imported explicitly. `run_cmd` is unavailable without
    it, and dumping a core-only environment is a legitimate thing to want — it
    is how you test this script in seconds instead of minutes.
  * The module name comes from the index/header pair, which is core. The
    convenience accessor is a library extension, so a version of this that used
    it worked against the full library and failed against core: the exact
    inversion of where you want a script to be robust.

Output is TSV on stdout, written in chunks. Joining half a million strings once
at the end dominates the entire run.

  lake env lean scripts/lean/DumpNames.lean > names.tsv
-/
import Lean.Elab.Command
import Mathlib

open Lean Elab Command in
run_cmd liftTermElabM do
  let env ← getEnv
  let stdout ← IO.getStdout
  let mut chunk : Array String := #[]
  let mut written := 0
  for (name, info) in env.constants.toList do
    if name.isInternal then continue
    let kind := match info with
      | .thmInfo _   => "theorem"
      | .axiomInfo _ => "axiom"
      | .defnInfo _  => "def"
      | _            => ""
    if kind == "" then continue
    let mod := match env.getModuleIdxFor? name with
      | some idx =>
        match env.header.moduleNames[idx.toNat]? with
          | some m => m.toString
          | none => ""
      | none => ""
    chunk := chunk.push s!"{name}\t{mod}\t{kind}"
    written := written + 1
    if chunk.size >= 5000 then
      stdout.putStr (String.intercalate "\n" chunk.toList ++ "\n")
      chunk := #[]
  if chunk.size > 0 then
    stdout.putStr (String.intercalate "\n" chunk.toList ++ "\n")
  stdout.flush
