#!/usr/bin/env python3
"""Improvise a provisional domain pack when no registered pack matches.

resolve_domain.py returning NO_MATCH leaves a run with two bad options and one
good one. The bad ones: refuse the problem outright, or proceed with no field
doctrine at all — which is the silent failure, because the roles still run, still
produce, and still sound confident. The good one is this: build a pack that is
honestly weaker than a registered one, work under it, and label everything it
produces as having been done under an improvised checker.

What a provisional pack is allowed to be:

- Real. The adapter it writes is a working checker, not a stub. It verifies the
  properties any field's artifact must have — no placeholders, every frozen
  obligation addressed, the target hash unchanged — and it can be run.
- Refutable. It ships a refute-attempt gate that perturbs the frozen claim and
  requires the verdict to flip. A checker that passes an artifact just as happily
  after an obligation is removed was never reading the obligations, and this
  catches exactly that.
- Capped. Whoever produces candidates here also wrote the thing that checks
  them. That is a conflict of interest, not a detail, so `provisional.ceiling`
  is SKETCH: work can proceed and be recorded, and it cannot reach the status a
  pack with an independent backend supports. Lifting the ceiling requires
  wiring a backend the run did not write — which is what the generated
  promotion checklist says.

Usage:
    scaffold_domain.py --domain <name> --from <template-pack> --statement "..."
    scaffold_domain.py --domain <name> --from <template-pack> --file problem.txt

Exit status: 0 written and conformant, 1 written but needs attention, 2 usage.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

SKILL_ROOT = Path(__file__).resolve().parent.parent
DOMAINS_DIR = SKILL_ROOT / "domains"

# Words that carry no field information. A signal drawn from this list would
# match every problem and turn resolution into noise.
STOPWORDS = {
    "about", "above", "after", "against", "already", "also", "another", "answer",
    "any", "anything", "approach", "argument", "around", "because", "been", "before",
    "being", "below", "best", "better", "between", "both", "build", "candidate",
    "cannot", "case", "cases", "change", "check", "claim", "claims", "come", "compare",
    "complete", "condition", "conditions", "consider", "correct", "could", "current",
    "data", "decide", "describe", "detail", "determine", "different", "does", "done",
    "during", "each", "either", "enough", "even", "every", "evidence", "example",
    "exist", "explain", "find", "first", "following", "form", "from", "full", "general",
    "give", "given", "good", "have", "here", "high", "hold", "holds", "however",
    "identify", "into", "issue", "just", "keep", "kind", "know", "known", "large",
    "last", "least", "less", "level", "like", "list", "long", "look", "made", "make",
    "many", "matter", "made", "mean", "might", "more", "most", "much", "must", "need",
    "never", "next", "none", "note", "number", "often", "only", "open", "order",
    "other", "over", "part", "particular", "possible", "practice", "present", "problem",
    "produce", "provide", "question", "range", "rather", "real", "reason", "report",
    "require", "required", "result", "results", "right", "same", "second", "seem",
    "several", "should", "show", "significant", "similar", "simple", "since", "small",
    "some", "something", "specific", "standard", "start", "state", "statement", "step",
    "still", "such", "sure", "take", "test", "than", "that", "their", "them", "then",
    "there", "these", "they", "thing", "think", "this", "those", "three", "through",
    "time", "true", "under", "understand", "until", "upon", "used", "using", "value",
    "verify", "very", "want", "well", "were", "what", "when", "where", "whether",
    "which", "while", "will", "with", "within", "without", "work", "would", "write",
}

MAX_SIGNALS = 12


def candidate_signals(statement: str, taken: set[str]) -> list[str]:
    """Distinctive words from the statement, in order of first appearance.

    Deliberately conservative. A term another pack already claims is skipped —
    an improvised pack must not start by stealing a registered pack's problems,
    and that failure would show up only as a wrong pack being loaded silently.
    """
    seen: list[str] = []
    for word in re.findall(r"[a-z][a-z-]{3,}", statement.lower()):
        if word in STOPWORDS or word in taken or word in seen:
            continue
        seen.append(word)
    return seen[:MAX_SIGNALS]


ADAPTER = '''#!/usr/bin/env python3
"""Provisional verification adapter — generated by scripts/scaffold_domain.py.

This checks the properties an artifact must have in ANY field. It is not a
substitute for this field's real backend; it is what makes work possible before
one exists, and its ceiling says so.

Three checks, all mechanical:

1. PLACEHOLDER — the artifact must not still contain a deferral token. An
   artifact that says it will do the hard part later has not done it.
2. COVERAGE — every obligation frozen into the claim must be addressed by name
   in the artifact. This is weak evidence that the obligation was met and strong
   evidence when it FAILS, which is the direction that matters.
3. TARGET — the claim's frozen hash must match the one the artifact was written
   against, so the statement cannot drift under the work.

`--refute` is the refute-attempt gate: it removes one obligation from the claim
and requires the verdict to flip to fail. A checker that passes just as happily
with an obligation missing is not reading the obligations at all.

Usage:
    check.py --artifact <path> --claim <claim.json> [--tier structural]
    check.py --artifact <path> --claim <claim.json> --refute
    check.py --self-test
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent

PLACEHOLDERS = ("TODO", "FIXME", "XXX", "TBD", "placeholder", "omitted", "left as an exercise")


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def check(artifact_text: str, claim: dict, artifact_path: str) -> dict:
    failures = []

    for token in PLACEHOLDERS:
        if re.search(rf"(?<![\\w-]){re.escape(token)}(?![\\w-])", artifact_text, re.IGNORECASE):
            failures.append({"check": "placeholder", "detail": f"artifact still contains {token!r}"})

    obligations = claim.get("obligations") or []
    normalized = artifact_text.lower()
    for obligation in obligations:
        oid = obligation.get("id") if isinstance(obligation, dict) else str(obligation)
        if not oid:
            continue
        if oid.lower() not in normalized:
            failures.append(
                {"check": "coverage", "detail": f"obligation {oid!r} is not addressed in the artifact"}
            )

    frozen = claim.get("target_sha256")
    if frozen:
        restated = claim.get("statement", "")
        if restated and sha256_text(restated) != frozen:
            failures.append(
                {"check": "target", "detail": "claim statement does not hash to its frozen target"}
            )

    return {
        "schema": "provisional-receipt-v1",
        "artifact": artifact_path,
        "artifact_sha256": sha256_text(artifact_text),
        "tier": "structural",
        "verdict": "fail" if failures else "pass",
        "failures": failures,
        "obligations_checked": len(obligations),
        "provisional": True,
        "ceiling": "SKETCH",
        "note": (
            "Produced by a provisional adapter written by the same system that produces "
            "candidates for it. This receipt supports SKETCH and nothing stronger."
        ),
    }


def refute(artifact_text: str, claim: dict, artifact_path: str) -> dict:
    """Perturb the claim and require the verdict to flip."""
    obligations = claim.get("obligations") or []
    if not obligations:
        return {
            "gate": "perturbed-recheck",
            "verdict": "fail",
            "detail": (
                "the claim froze no obligations, so there is nothing to perturb and nothing "
                "this adapter can meaningfully check. Freeze obligations before claiming a pass."
            ),
        }
    weakened = dict(claim)
    dropped = obligations[0]
    weakened["obligations"] = obligations[1:] + [{"id": "__perturbed_obligation__"}]
    result = check(artifact_text, weakened, artifact_path)
    flipped = result["verdict"] == "fail"
    return {
        "gate": "perturbed-recheck",
        "verdict": "pass" if flipped else "fail",
        "perturbation": "replaced one frozen obligation with one the artifact cannot address",
        "dropped": dropped,
        "detail": (
            "verdict flipped under perturbation, so the checker is reading the claim"
            if flipped
            else "verdict did NOT flip: this adapter is not actually reading the obligations, "
                 "and its passes are worthless until that is fixed"
        ),
    }


def self_test() -> int:
    control_dir = HERE / "negative_control"
    claim = json.loads((control_dir / "claim.json").read_text(encoding="utf-8"))
    failed = []
    for path in sorted(control_dir.glob("bad_*")):
        result = check(path.read_text(encoding="utf-8"), claim, path.name)
        if result["verdict"] != "fail":
            failed.append(path.name)
    good = control_dir / "good.txt"
    if good.exists():
        result = check(good.read_text(encoding="utf-8"), claim, good.name)
        if result["verdict"] != "pass":
            failed.append(f"{good.name} (should pass, did not: {result['failures']})")
    if failed:
        print("SELF-TEST FAIL: " + ", ".join(failed))
        return 1
    print("SELF-TEST PASS: every known-bad control was rejected and the known-good one passed")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\\n")[0])
    parser.add_argument("--artifact")
    parser.add_argument("--claim")
    parser.add_argument("--tier", default="structural")
    parser.add_argument("--refute", action="store_true")
    parser.add_argument("--self-test", action="store_true")
    args = parser.parse_args()

    if args.self_test:
        return self_test()
    if not (args.artifact and args.claim):
        parser.error("--artifact and --claim are required unless --self-test")

    artifact_text = Path(args.artifact).read_text(encoding="utf-8")
    claim = json.loads(Path(args.claim).read_text(encoding="utf-8"))
    result = refute(artifact_text, claim, args.artifact) if args.refute \\
        else check(artifact_text, claim, args.artifact)
    print(json.dumps(result, indent=2))
    return 0 if result["verdict"] == "pass" else 1


if __name__ == "__main__":
    sys.exit(main())
'''

CONTROL_CLAIM = {
    "claim_id": "control-1",
    "statement": "The generated report addresses every frozen obligation.",
    "obligations": [{"id": "OBL-1"}, {"id": "OBL-2"}],
}

CONTROLS = {
    "good.txt": (
        "Response to OBL-1: the first obligation is addressed here, in full.\n"
        "Response to OBL-2: the second obligation is addressed here, in full.\n"
    ),
    "bad_placeholder.txt": (
        "Response to OBL-1: addressed.\n"
        "Response to OBL-2: TODO — will finish this part later.\n"
    ),
    "bad_missing_obligation.txt": (
        "Response to OBL-1: addressed, at length, with supporting detail.\n"
        "The second requirement is not mentioned anywhere in this document.\n"
    ),
}

DOCTRINE_HEADER = """# {title} doctrine — {domain} (PROVISIONAL)

> This pack was improvised because no registered pack matched the incoming
> problem. Everything below is a starting point derived from the frame and from
> `{template}`'s shape — not from experience in this field. Treat every rule here
> as a hypothesis about how this field works, and correct it from what actually
> happens on the first real run.

**Ceiling: SKETCH.** The adapter here was written by the same system that
produces candidates for it, so nothing produced under this pack may be reported
as verified. Say "SKETCH under a provisional pack" and mean it.

"""

EXPLORER_BODY = """## Freezing a target here

The frame requires a target that cannot drift. This field's frozen form is not
yet known, so freeze the **verbatim statement plus an explicit obligation list**:
each thing that must hold for the claim to be true, given an id. The provisional
adapter checks coverage against exactly those ids, so an obligation you leave out
is one nothing will ever ask about.

## Retrieval

There is no corpus declared for this field yet. Until there is, retrieval is
manual and must be recorded: what was searched, where, and what came back empty.
An empty result is information; an unrecorded search is not.

## Tier selection

One tier exists, it is cheap, and it caps at SKETCH. So tier selection is not a
decision yet — the decision is whether the problem can usefully be worked at
SKETCH at all. If it cannot, say so and stop rather than producing a confident
artifact nothing can check.

## What to escalate

Escalate to the Researcher after {escalate} consecutive failures on one frozen
claim, as the frame requires. In a field this pack does not yet understand, also
escalate the first time a failure is not explainable — an unexplained failure in
an unmodelled field is more informative than three explainable ones.
"""

GENERATOR_BODY = """## Producing here

Produce an artifact that names every frozen obligation id and addresses it under
that name. This is a low bar and it is the only bar the provisional adapter can
enforce; clearing it is not evidence of correctness, and failing it is evidence
of incorrectness. Aim well above it.

## Submitting

```bash
python3 adapter/check.py --artifact <file> --claim <claim.json>
python3 adapter/check.py --artifact <file> --claim <claim.json> --refute
```

Both must pass. The second is the refute-attempt gate: it perturbs the claim and
requires the verdict to flip. If it does not flip, stop — the checker is not
reading the claim, and its passes mean nothing until that is fixed.

## What you may not do

Do not edit the frozen claim to make an artifact pass. Do not report a pass from
this adapter as verification. Do not accept your own work: the frame's rule holds
here with more force than usual, because the checker is not independent either.
"""

RESEARCHER_BODY = """## Attacking an obstruction here

The obstruction catalogue for this field does not exist yet, so build it as you
go. For each obstruction that stops production, record: what was attempted, the
exact way it failed, and whether the failure is about this instance or about the
approach. The second kind is what makes a catalogue worth having.

## Refutation first

Spend the first part of every attack trying to show the claim is FALSE. In a
field with no independent backend, a refutation you can exhibit is worth more
than a supporting argument nothing can check — it is the only result here that
does not depend on trusting the producer.

## Handing back

Return an obstruction record, not a verdict. Closing a target is Explorer's
decision, and under a provisional pack the strongest available close is SKETCH.
"""

PROMOTION = [
    "Wire a verification backend this run did not write, and declare its authorship as independent.",
    "Register a negative control that backend demonstrably rejects, so `adversarial` stops being a self-report.",
    "Replace the generated signal list with terms drawn from real problems in this field, and add counter_examples.",
    "Rewrite all three role doctrine files from what actually happened on real runs, not from the template.",
    "Declare the field's own claim schema and receipt format, replacing the generic ones.",
]


def write(path: Path, text: str, executable: bool = False) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    if executable:
        path.chmod(0o755)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--domain", required=True, help="pack name; becomes the directory name")
    parser.add_argument("--from", dest="template", required=True, help="registered pack to copy the SHAPE of")
    source = parser.add_mutually_exclusive_group(required=True)
    source.add_argument("--statement", help="the problem that found no pack")
    source.add_argument("--file", help="file holding that problem")
    parser.add_argument("--reason", help="why no registered pack fit; defaults to a stated fallback")
    parser.add_argument("--force", action="store_true", help="overwrite an existing directory")
    args = parser.parse_args()

    if not re.fullmatch(r"[a-z0-9][a-z0-9-]*", args.domain):
        print("ERROR: pack names are lowercase, digits and hyphens; a leading underscore is "
              "reserved for frame fixtures", file=sys.stderr)
        return 2

    pack_dir = DOMAINS_DIR / args.domain
    if pack_dir.exists() and not args.force:
        print(f"ERROR: {pack_dir} already exists. Use --force to overwrite.", file=sys.stderr)
        return 2

    template_dir = DOMAINS_DIR / args.template
    if not (template_dir / "domain.json").is_file():
        print(f"ERROR: no template pack at {template_dir}", file=sys.stderr)
        return 2
    template = json.loads((template_dir / "domain.json").read_text(encoding="utf-8"))

    statement = args.statement
    if args.file:
        statement = Path(args.file).read_text(encoding="utf-8")

    taken: set[str] = set()
    for entry in sorted(DOMAINS_DIR.iterdir()):
        manifest = entry / "domain.json"
        if manifest.is_file():
            pack = json.loads(manifest.read_text(encoding="utf-8"))
            selection = pack.get("selection") or {}
            for field in ("signals", "strong_signals"):
                taken.update(t.lower() for t in selection.get(field, []) or [])

    signals = candidate_signals(statement, taken)
    if len(signals) < 3:
        print(
            "ERROR: fewer than three distinctive terms in this statement, so the pack could not "
            "be resolved back to reliably. Supply a fuller statement, or write the pack by hand.",
            file=sys.stderr,
        )
        return 2

    escalate = ((template.get("doctrine") or {}).get("escalation") or {}).get(
        "max_consecutive_failures", 3
    )

    manifest = {
        "contract_version": "2",
        "domain": args.domain,
        "description": (
            f"PROVISIONAL pack improvised for a problem no registered pack matched. "
            f"Templated from {args.template}. Its adapter checks field-independent properties "
            f"only and caps at SKETCH."
        ),
        "selection": {
            "signals": signals,
            "examples": [" ".join(statement.split())[:400]],
            "min_score": 3,
        },
        "provisional": {
            "reason": args.reason or (
                "resolve_domain.py returned NO_MATCH for this problem and no registered pack "
                "covers the field; work proceeds under a capped improvised pack rather than "
                "under no doctrine at all"
            ),
            "authored_by": "orchestrator",
            "created_from": args.template,
            "ceiling": "SKETCH",
            "promotion_requirements": PROMOTION,
        },
        "verification_adapter": {
            "entry_point": "adapter/check.py",
            "tiers": [
                {
                    "name": "structural",
                    "description": (
                        "Field-independent artifact check: no placeholder tokens, every frozen "
                        "obligation addressed by name, frozen target hash unchanged. Real and "
                        "runnable, and weak by construction."
                    ),
                    "adversarial": False,
                    "cost_hint": "cheap",
                    "max_status": "SKETCH",
                    "authorship": "same_author_as_producer",
                    "contamination_controls": (
                        "Reads only the artifact and the frozen claim. It has no access to a "
                        "reference answer, because none exists for this field yet."
                    ),
                    "availability_check": "python3 adapter/check.py --self-test",
                    "negative_control": "adapter/negative_control",
                }
            ],
        },
        "claim_schema": {
            "path": "claim.schema.json",
            "extends": "frame-claim-v1",
            "additional_required_fields": ["obligations"],
        },
        "receipt_format": {
            "path": "receipt.schema.json",
            "required_fields": ["artifact_sha256", "verdict", "tier", "provisional"],
            "freshness_rule": (
                "The receipt records the artifact's SHA-256 at check time and is stale the moment "
                "the artifact's current hash differs. The exit gate recomputes rather than "
                "trusting the recorded value."
            ),
        },
        "doctrine": {
            "escalation": {
                "max_consecutive_failures": escalate,
                "failure_signature": (
                    "The pair (check name, first failure detail with paths and indexes stripped). "
                    "A repeat of the same pair escalates immediately: the second attempt changed "
                    "nothing the checker could see."
                ),
            },
            "roles": {
                "explorer": "doctrine/explorer.md",
                "generator": "doctrine/generator.md",
                "researcher": "doctrine/researcher.md",
            },
            "rules": ["doctrine/provisional.md"],
        },
        "gates": {
            "refute_attempt": {
                "name": "perturbed-recheck",
                "description": (
                    "Re-runs the adapter against a perturbed claim and requires the verdict to "
                    "flip to fail. No tier here is adversarial, so the gate is a genuinely "
                    "separate step rather than a second friendly run."
                ),
            },
            "additional": [
                {
                    "name": "placeholder-scan",
                    "description": "Rejects an artifact still containing a deferral token.",
                    "blocking": True,
                }
            ],
        },
    }

    write(pack_dir / "domain.json", json.dumps(manifest, indent=2) + "\n")
    write(pack_dir / "adapter" / "check.py", ADAPTER, executable=True)
    write(
        pack_dir / "adapter" / "negative_control" / "claim.json",
        json.dumps(CONTROL_CLAIM, indent=2) + "\n",
    )
    for name, body in CONTROLS.items():
        write(pack_dir / "adapter" / "negative_control" / name, body)

    write(pack_dir / "claim.schema.json", json.dumps({
        "$schema": "http://json-schema.org/draft-07/schema#",
        "$id": f"{args.domain}-claim-v1",
        "description": (
            "Provisional claim schema: the frame's generic claim plus an explicit obligation "
            "list, which is what the provisional adapter checks coverage against."
        ),
        "type": "object",
        "required": ["claim_id", "statement", "target_sha256", "obligations"],
        "properties": {
            "claim_id": {"type": "string"},
            "statement": {"type": "string", "minLength": 1},
            "target_sha256": {"type": "string", "pattern": "^[0-9a-f]{64}$"},
            "obligations": {
                "description": "Each thing that must hold for the claim to be true. An obligation "
                               "left off this list is one nothing will ever ask about.",
                "type": "array",
                "minItems": 1,
                "items": {
                    "type": "object",
                    "required": ["id", "text"],
                    "properties": {"id": {"type": "string"}, "text": {"type": "string"}},
                },
            },
        },
    }, indent=2) + "\n")

    write(pack_dir / "receipt.schema.json", json.dumps({
        "$schema": "http://json-schema.org/draft-07/schema#",
        "$id": f"{args.domain}-receipt-v1",
        "description": "What the provisional adapter emits. `provisional` is required and true, "
                       "so a receipt from here can never be mistaken for one from a real backend.",
        "type": "object",
        "required": ["artifact_sha256", "verdict", "tier", "provisional", "ceiling"],
        "properties": {
            "artifact_sha256": {"type": "string", "pattern": "^[0-9a-f]{64}$"},
            "verdict": {"enum": ["pass", "fail"]},
            "tier": {"type": "string"},
            "failures": {"type": "array", "items": {"type": "object"}},
            "provisional": {"const": True},
            "ceiling": {"const": "SKETCH"},
        },
    }, indent=2) + "\n")

    for role, title, body in (
        ("explorer", "Explorer", EXPLORER_BODY),
        ("generator", "Generator", GENERATOR_BODY),
        ("researcher", "Researcher", RESEARCHER_BODY),
    ):
        header = DOCTRINE_HEADER.format(title=title, domain=args.domain, template=args.template)
        write(pack_dir / "doctrine" / f"{role}.md", header + body.format(escalate=escalate))

    write(pack_dir / "doctrine" / "provisional.md", f"""# Provisional pack rules — {args.domain}

This pack exists so a run in an unregistered field can proceed honestly. Four
rules hold for everything done under it.

1. **Nothing here reaches VERIFIED.** The ceiling is SKETCH and it is declared in
   the manifest, checked by `scripts/validate_domain_pack.py`, and repeated on
   every receipt. The reason is not caution — it is that the checker and the
   producer are the same system.
2. **Every report says "provisional".** A reader who is not told which pack
   produced a result will assume it was a real one.
3. **The improvised signal list is a guess.** It was generated from one problem
   statement. The first time this pack is loaded for a problem it should not
   have taken, narrow it — a pack that steals another pack's problems is worse
   than no pack, because the failure is silent.
4. **Promotion is a checklist, not a feeling.** The manifest's
   `provisional.promotion_requirements` names what must exist before this stops
   being provisional. Until every item is done, it is provisional no matter how
   well it has been working.
""")

    print(f"Wrote provisional pack: {pack_dir.relative_to(SKILL_ROOT)}/")
    print(f"  signals drawn from the statement: {', '.join(signals)}")
    print(f"  ceiling: SKETCH — an orchestrator-authored adapter cannot support more\n")

    status = 0
    for label, cmd in (
        ("adapter self-test", [sys.executable, str(pack_dir / "adapter" / "check.py"), "--self-test"]),
        ("pack conformance", [sys.executable, str(SKILL_ROOT / "scripts" / "validate_domain_pack.py"),
                              str(pack_dir / "domain.json")]),
        ("resolution self-test", [sys.executable, str(SKILL_ROOT / "scripts" / "resolve_domain.py"),
                                  "--self-test"]),
    ):
        proc = subprocess.run(cmd, capture_output=True, text=True)
        mark = "ok" if proc.returncode == 0 else "NEEDS ATTENTION"
        print(f"  {label}: {mark}")
        if proc.returncode != 0:
            status = 1
            for line in (proc.stdout + proc.stderr).strip().splitlines():
                print(f"      {line}")

    if status:
        print(
            "\nThe pack was written but is not yet conformant. Fix the items above before "
            "working under it; a pack that fails its own checks will fail them silently later."
        )
    else:
        print("\nReady. Load it with: python3 scripts/resolve_domain.py --domain " + args.domain)
    return status


if __name__ == "__main__":
    sys.exit(main())
